/**
 * ============================================================================
 * MODULAR FIGMA VARIABLE ORCHESTRATOR
 * Organization:
 * 1. UI Initialization
 * 2. Message Router (Main entry point)
 * 3. Export Formatters (String generation for CSV/CSS/JSON)
 * 4. Figma Variable API (CRUD operations)
 * 5. Color Logic Engine (Generation & Mapping)
 * 6. Mathematical Utilities (Color math & HSL/RGB)
 * ============================================================================
 */

// 1. UI INITIALIZATION
figma.showUI(__html__, { width: 424, height: 720, themeColors: true });

// 2. MESSAGE ROUTER
figma.ui.onmessage = async (msg) => {
  try {
    switch (msg.type) {
      case "run-creater": {
        const tokenState = msg.state;
        const processedData = ColorEngine.process(tokenState);
        await VariableManager.sync(processedData, msg.scope || "all");
        break;
      }

      case "resize":
        figma.ui.resize(msg.width, msg.height);
        break;

      case "request-processed-data": {
        const tokenState = msg.state;
        const processedData = ColorEngine.process(tokenState);
        let content = "";

        if (msg.exportType === "json") content = JSON.stringify(processedData, null, 2);
        else if (msg.exportType === "csv") content = ExportFormatter.toCSV(processedData);
        else if (msg.exportType === "css") content = ExportFormatter.toCSS(processedData);

        figma.ui.postMessage({ type: "processed-data-response", content, exportType: msg.exportType });
        break;
      }

      case "cancel":
        figma.closePlugin();
        break;
    }
  } catch (err) {
    console.error("Plugin Error:", err);
    figma.ui.postMessage({ type: "error", message: err.message || "Unknown error" });
  }
};

// 3. EXPORT FORMATTERS
const ExportFormatter = {
  toCSV(data) {
    let csv = "Group,Weight,Token Name,Value,Contrast (Light),Contrast (Dark)\n";
    data.colorWeights.collection.forEach((group) => {
      group.colorWeights.forEach((w) => {
        csv += `${group.colorName},${w.weight},${w.name},${w.value},${w.contrast.light.ratio},${w.contrast.dark.ratio}\n`;
      });
    });
    return csv;
  },

  toCSS(data) {
    let css = `:root {\n  /* Generated by ${data.colorSystemConfig.designSystemName} */\n\n  /* Raw Color Ramp */\n`;
    data.colorWeights.collection.forEach((group) => {
      group.colorWeights.forEach((w) => {
        css += `  --${w.name.toLowerCase().replace(/\//g, "-")}: ${w.value};\n`;
      });
    });

    ["light", "dark"].forEach((theme) => {
      css += `\n  /* Contextual Tokens (${theme.toUpperCase()}) */\n`;
      data.roleTokens[theme].roleTokensCollection.forEach((roleGroup) => {
        roleGroup.variations.forEach((v) => {
          const varName = `--${v.roleTokenName.toLowerCase().replace(/\//g, "-")}-${theme}`;
          css += `  ${varName}: ${v.value};\n`;
        });
      });
    });
    css += "}\n";
    return css;
  },
};

// 4. FIGMA VARIABLE API (CRUD)
const VariableManager = {
  tally: { created: 0, updated: 0, failed: 0 },
  cache: { variables: [], collections: [] },

  async sync(processedData, scope = "all") {
    this.tally = { created: 0, updated: 0, failed: 0 };
    await this.refreshCache();

    // STAGE 1: RAW Ramps
    if (scope === "all" || scope === "groups") {
      const rawCol = await this.getOrCreateCollection("_raw");
      const modeId = rawCol.modes[0].modeId;
      for (const group of processedData.colorWeights.collection) {
        const vars = group.colorWeights.map((w) => [w.name, "COLOR", w.value, `Contrast: L ${w.contrast.light.ratio} (${w.contrast.light.rating}), D ${w.contrast.dark.ratio} (${w.contrast.dark.rating})`]);
        await this.upsertVariables(rawCol, modeId, vars);
      }
    }

    // STAGE 2: Contextual Roles
    if (scope === "all" || scope === "roles") {
      const contextualCol = await this.getOrCreateCollection("contextual");
      const rawCol = await this.getOrCreateCollection("_raw");

      for (const theme of ["light", "dark"]) {
        const modeId = this.ensureMode(contextualCol, theme);
        for (const roleGroup of processedData.roleTokens[theme].roleTokensCollection) {
          const vars = roleGroup.variations.map((v) => {
            const targetVar = this.cache.variables.find((cv) => cv.name === v.refWeightToken && cv.variableCollectionId === rawCol.id);
            const valueAlias = targetVar ? { type: "VARIABLE_ALIAS", id: targetVar.id } : null;
            return [`${v.roleTokenName}`, "COLOR", valueAlias, `Theme: ${theme.toUpperCase()} | Variation: ${v.variationName}`];
          });
          await this.upsertVariables(contextualCol, modeId, vars);
        }
      }
    }

    figma.ui.postMessage({ type: "finish", tally: this.tally });
  },

  async refreshCache() {
    this.cache.variables = await figma.variables.getLocalVariablesAsync();
    this.cache.collections = await figma.variables.getLocalVariableCollectionsAsync();
  },

  async getOrCreateCollection(name) {
    const existing = this.cache.collections.find((c) => c.name === name);
    if (existing) return existing;
    const newCol = figma.variables.createVariableCollection(name);
    this.cache.collections.push(newCol);
    return newCol;
  },

  ensureMode(collection, modeName) {
    const existing = collection.modes.find((m) => m.name.toLowerCase() === modeName.toLowerCase());
    if (existing) return existing.modeId;
    if (collection.modes.length === 1 && collection.modes[0].name.toLowerCase().startsWith("mode")) {
      collection.renameMode(collection.modes[0].modeId, modeName);
      return collection.modes[0].modeId;
    }
    try {
      return collection.addMode(modeName);
    } catch (e) {
      return collection.modes[0].modeId;
    }
  },

  async upsertVariables(collection, modeId, vars) {
    for (const [varName, varType, varValue, varDescription] of vars) {
      try {
        let variable = this.cache.variables.find((v) => v.name === varName && v.variableCollectionId === collection.id);
        if (!variable) {
          variable = figma.variables.createVariable(varName, collection, varType);
          this.cache.variables.push(variable);
          this.tally.created++;
        } else {
          this.tally.updated++;
        }
        if (varDescription) variable.description = varDescription;
        if (varValue !== undefined) {
          if (varType === "COLOR" && typeof varValue === "string") {
            const rgb = ColorUtils.hexToRgb(varValue);
            variable.setValueForMode(modeId, { r: rgb.r / 255, g: rgb.g / 255, b: rgb.b / 255 });
          } else {
            variable.setValueForMode(modeId, varValue);
          }
        }
      } catch (err) {
        this.tally.failed++;
      }
    }
  },
};

// 5. COLOR LOGIC ENGINE
const ColorEngine = {
  process(config) {
    const lightBg = config.lightBg.startsWith("#") ? config.lightBg : "#" + config.lightBg;
    const darkBg = config.darkBg.startsWith("#") ? config.darkBg : "#" + config.darkBg;

    const colors = {
      collection: config.clrGroups.map((group) => ({
        colorName: group.name,
        colorNameShort: group.shortName,
        colorWeights: this.colorWeightsMaker(group, config.weightsCount, config.weightNames, config.weightsMethod),
      })),
    };

    const roles = {
      light: this.colorRolesMaker(config.roles, config.roleVariationsNames, colors, config.roleMappingMethod, { name: "light", bg: lightBg }),
      dark: this.colorRolesMaker(config.roles, config.roleVariationsNames, colors, config.roleMappingMethod, { name: "dark", bg: darkBg }),
    };

    return { colorSystemConfig: config, colorWeights: colors, roleTokens: roles };
  },

  colorWeightsMaker(group, count, weightNamesStr, method) {
    const weightNames = weightNamesStr && weightNamesStr.trim() !== "" ? weightNamesStr.split(",").map((n) => n.trim()) : Array.from({ length: count }, (_, i) => (i + 1).toString());
    const seed = ColorUtils.normalizeHex(group.value) || "#000000";
    let hexRamp = [];

    if (method === "Gradual") hexRamp = ColorUtils.generateGradualGradient(seed, count);
    else if (method === "Balanced") hexRamp = ColorUtils.generateBalancedShades(seed, count);
    else if (method === "Uniform") hexRamp = ColorUtils.generateUniformSteps(seed, count);
    else hexRamp = ColorUtils.generateBalancedShades(seed, count);

    return hexRamp.map((hex, i) => ({
      name: `${group.name}/${weightNames[i] || i + 1}`,
      nameShort: `${group.shortName}/${weightNames[i] || i + 1}`,
      value: hex,
      weight: i + 1,
      contrast: {
        dark: ColorUtils.getContrast(hex, "#000000"),
        light: ColorUtils.getContrast(hex, "#FFFFFF"),
      },
    }));
  },

  colorRolesMaker(roleInputs, variationsNames, colorTokens, method, theme) {
    const variations = (variationsNames || "lighter, light, base, dark, darker").split(",").map((v) => v.trim());
    const centerIdx = Math.floor(variations.length / 2);
    const { name: themeName, bg } = theme;
    const roleTokensCollection = [];

    colorTokens.collection.forEach((group) => {
      Object.entries(roleInputs).forEach(([roleId, role]) => {
        const spread = parseInt(role.spread) || 1;
        let baseWeightIdx = -1;

        if (method === "Contrast-Based") {
          const minC = parseFloat(role.minContrast) || 4.5;
          if (themeName === "light") {
            for (let i = 0; i < group.colorWeights.length; i++) {
              if (ColorUtils.contrastRatio(group.colorWeights[i].value, bg) >= minC) {
                baseWeightIdx = i;
                break;
              }
            }
          } else {
            for (let i = group.colorWeights.length - 1; i >= 0; i--) {
              if (ColorUtils.contrastRatio(group.colorWeights[i].value, bg) >= minC) {
                baseWeightIdx = i;
                break;
              }
            }
          }
        } else {
          baseWeightIdx = (parseInt(role.baseWeight) || 1) - 1;
        }

        if (baseWeightIdx === -1) baseWeightIdx = Math.floor(group.colorWeights.length / 2);

        const varTokens = variations.map((v, i) => {
          const stepOffset = i - centerIdx;
          let wIdx = themeName === "light" ? baseWeightIdx + stepOffset * spread : baseWeightIdx - stepOffset * spread;
          wIdx = Math.max(0, Math.min(group.colorWeights.length - 1, wIdx));
          const targetToken = group.colorWeights[wIdx];

          return {
            variationName: v,
            roleTokenName: `${group.colorName}/${role.name}/${v}`,
            roleTokenNameShort: `${group.colorNameShort}/${role.shortName}/${v}`,
            refWeightToken: targetToken.name,
            value: targetToken.value,
            contrast: {
              dark: ColorUtils.getContrast(targetToken.value, "#000000"),
              light: ColorUtils.getContrast(targetToken.value, "#FFFFFF"),
            },
          };
        });

        roleTokensCollection.push({
          roleName: `${group.colorName} ${role.name}`,
          roleNameShort: `${group.colorNameShort}${role.shortName}`,
          variations: varTokens,
        });
      });
    });

    return { roleTokensCollection };
  },
};

// 6. MATHEMATICAL UTILITIES
const ColorUtils = {
  normalizeHex(hex) {
    if (!hex) return null;
    let h = hex.toString().replace("#", "").toUpperCase();
    if (h.length === 3)
      h = h
        .split("")
        .map((c) => c + c)
        .join("");
    return h.length === 6 ? "#" + h : null;
  },

  hexToRgb(hex) {
    const h = this.normalizeHex(hex);
    if (!h) return { r: 0, g: 0, b: 0 };
    return { r: parseInt(h.substring(1, 3), 16), g: parseInt(h.substring(3, 5), 16), b: parseInt(h.substring(5, 7), 16) };
  },

  rgbToHex(r, g, b) {
    const f = (v) =>
      Math.round(Math.max(0, Math.min(255, v)))
        .toString(16)
        .padStart(2, "0")
        .toUpperCase();
    return `#${f(r)}${f(g)}${f(b)}`;
  },

  rgbToHsl(r, g, b) {
    r /= 255;
    g /= 255;
    b /= 255;
    const max = Math.max(r, g, b),
      min = Math.min(r, g, b);
    let h,
      s,
      l = (max + min) / 2;
    if (max === min) h = s = 0;
    else {
      const d = max - min;
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
      switch (max) {
        case r:
          h = (g - b) / d + (g < b ? 6 : 0);
          break;
        case g:
          h = (b - r) / d + 2;
          break;
        case b:
          h = (r - g) / d + 4;
          break;
      }
      h /= 6;
    }
    return { h: h * 360, s: s * 100, l: l * 100 };
  },

  hslToRgb(h, s, l) {
    h /= 360;
    s /= 100;
    l /= 100;
    let r, g, b;
    if (s === 0) r = g = b = l;
    else {
      const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
      const p = 2 * l - q;
      const f = (p, q, t) => {
        if (t < 0) t += 1;
        if (t > 1) t -= 1;
        if (t < 1 / 6) return p + (q - p) * 6 * t;
        if (t < 1 / 2) return q;
        if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
        return p;
      };
      r = f(p, q, h + 1 / 3);
      g = f(p, q, h);
      b = f(p, q, h - 1 / 3);
    }
    return { r: r * 255, g: g * 255, b: b * 255 };
  },

  getLuminance(r, g, b) {
    const f = (c) => {
      c /= 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    };
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
  },

  contrastRatio(hex1, hex2) {
    const r1 = this.hexToRgb(hex1),
      r2 = this.hexToRgb(hex2);
    const l1 = this.getLuminance(r1.r, r1.g, r1.b),
      l2 = this.getLuminance(r2.r, r2.g, r2.b);
    return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
  },

  getContrast(hex, bgHex) {
    const ratio = this.contrastRatio(hex, bgHex);
    let rating = "Fail";
    if (ratio >= 7) rating = "AAA";
    else if (ratio >= 4.5) rating = "AA";
    else if (ratio >= 3) rating = "AA Large";
    return { ratio: parseFloat(ratio.toFixed(2)), rating };
  },

  generateBalancedShades(hex, weights) {
    const rgb = this.hexToRgb(hex),
      hsl = this.rgbToHsl(rgb.r, rgb.g, rgb.b);
    const colors = new Array(weights),
      middle = Math.floor(weights / 2);
    colors[middle] = hex;
    for (let i = 0; i < middle; i++) {
      const p = (middle - i) / middle,
        maxL = Math.min(98, hsl.l + (100 - hsl.l) * 0.85);
      const res = this.hslToRgb(hsl.h, hsl.s, hsl.l + (maxL - hsl.l) * p);
      colors[i] = this.rgbToHex(res.r, res.g, res.b);
    }
    for (let i = middle + 1; i < weights; i++) {
      const p = (i - middle) / (weights - middle - 1),
        minL = Math.max(3, hsl.l * 0.1);
      const res = this.hslToRgb(hsl.h, hsl.s, hsl.l - (hsl.l - minL) * p);
      colors[i] = this.rgbToHex(res.r, res.g, res.b);
    }
    return colors;
  },

  generateGradualGradient(hex, weights) {
    const rgb = this.hexToRgb(hex),
      hsl = this.rgbToHsl(rgb.r, rgb.g, rgb.b);
    const colors = [];
    for (let i = 0; i < weights; i++) {
      const res = this.hslToRgb(hsl.h, hsl.s, 95 - (i / (weights - 1)) * 75);
      colors.push(this.rgbToHex(res.r, res.g, res.b));
    }
    return colors;
  },

  generateUniformSteps(hex, weights) {
    const rgb = this.hexToRgb(hex),
      hsl = this.rgbToHsl(rgb.r, rgb.g, rgb.b);
    const colors = [];
    for (let i = 0; i < weights; i++) {
      const progress = 1 - i / (weights - 1); // High L (Light) to Low L (Dark)
      const target = 1.1 + (21 - 1.1) * Math.pow(progress, 1.5);
      let low = 0,
        high = 100,
        bestL = 0,
        bestD = Infinity;
      for (let j = 0; j < 20; j++) {
        const mid = (low + high) / 2,
          tr = this.hslToRgb(hsl.h, hsl.s, mid);
        const actual = (this.getLuminance(tr.r, tr.g, tr.b) + 0.05) / 0.05;
        if (Math.abs(actual - target) < bestD) {
          bestD = Math.abs(actual - target);
          bestL = mid;
        }
        if (actual < target) low = mid;
        else high = mid;
      }
      const fr = this.hslToRgb(hsl.h, hsl.s, bestL);
      colors.push(this.rgbToHex(fr.r, fr.g, fr.b));
    }
    return colors;
  },
};
